### ISSUE TITLE
Not working in GitLab CI

### ISSUE THREAD

**Issue by iBobik** [18F/html-proofer-docker#6]
I have static web in GitLab and I want to test it by HTML proofer.

This .gilab-ci.yml works:
```yaml
test:
  image: ruby:2
  script:
    - bundle install
    - htmlproofer --empty-alt-ignore
```

But using this image it does not work:
```yaml
test:
  image: 18fgsa/html-proofer
  script:
    - htmlproofer --empty-alt-ignore
```

Command `gitlab-ci-multi-runner exec docker test` outputs:
```
Running with gitlab-ci-multi-runner 1.11.1 (a67a225)
  on  ()
Using Docker executor with image 18fgsa/html-proofer ...
Pulling docker image 18fgsa/html-proofer ...
Running on runner--project-1-concurrent-0 via Bobik-MacBook-Air.local...
Cloning repository...
Cloning into '/builds/project-1'...
done.
Checking out d601a1b8 as patch-4...
Skipping Git submodules setup
/usr/local/bundle/gems/mercenary-0.3.6/lib/mercenary/program.rb:31:in `go': ambiguous option: -c (OptionParser::AmbiguousOption)
	from /usr/local/bundle/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
	from /usr/local/bundle/gems/html-proofer-3.0.6/bin/htmlproofer:9:in `<top (required)>'
	from /usr/local/bundle/bin/htmlproofer:22:in `load'
	from /usr/local/bundle/bin/htmlproofer:22:in `<main>'
/usr/local/bundle/gems/mercenary-0.3.6/lib/mercenary/program.rb:31:in `go': ambiguous option: -c (OptionParser::AmbiguousOption)
	from /usr/local/bundle/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
	from /usr/local/bundle/gems/html-proofer-3.0.6/bin/htmlproofer:9:in `<top (required)>'
	from /usr/local/bundle/bin/htmlproofer:22:in `load'
	from /usr/local/bundle/bin/htmlproofer:22:in `<main>'
ERROR: Job failed: exit code 1
FATAL: exit code 1 
```

Even this does not work (error is the same):
```yaml
test:
  image: 18fgsa/html-proofer
  script:
    - echo "test"
```
